Setting up to run simple pytest
PeverellBrothers/DeepCite pull request #16
Opened 2017-10-09 03:05 UTC by johnjackoleary

Start moving towards a model of unit tests for key functions. Enable a
first test and get Travis CI running Pytest.

2017-10-09 03:32 UTC, connorjoleary requested changes
Shouldn't we separate the be all end all function from the tests?

2017-10-09 05:32 UTC, johnjackoleary commented
Depends on what it does I suppose. I actually haven't looked at the code yet. I've just been getting automated testing in place. Can I get it in a followup PR? (Or you can I suppose, if you want)

2017-10-10 02:26 UTC, connorjoleary commented
That sounds good, but just so you are aware that function is basically what calls all the other functions

2017-10-10 02:26 UTC, connorjoleary approved these changes

2017-10-10 02:26 UTC, merged